Repository Leets-Official/Yes-BE, pull requests merged in 2025-01, with the labels that each got.

#4 feat: 공통 응답 객체 구현
  .github/workflows/ci.yml
  build.gradle.kts
  module-independent/build.gradle.kts
  module-independent/src/main/kotlin/site/yourevents/error/exception/ServiceException.kt
  module-independent/src/main/kotlin/site/yourevents/response/ApiResponse.kt
  module-independent/src/main/kotlin/site/yourevents/type/ErrorCode.kt
  module-independent/src/main/kotlin/site/yourevents/type/SuccessCode.kt
  module-independent/src/test/kotlin/site/yourevents/response/ApiResponseTest.kt
  module-infrastructure/security/build.gradle.kts
  module-infrastructure/security/src/main/kotlin/site/yourevents/SecurityConfig.kt
  module-presentation/src/main/resources/application.yml
  settings.gradle.kts
Labels: ✨ feature, ⚙️ chore

#7 chore: 인프라 구축
  .github/workflows/ci-cd.yml
  Dockerfile
  build.gradle.kts
  module-infrastructure/security/src/main/kotlin/site/yourevents/SecurityConfig.kt
  module-presentation/build.gradle.kts
  module-presentation/src/main/kotlin/site/yourevents/config/jasypt/JasyptConfig.kt
  module-presentation/src/main/kotlin/site/yourevents/config/swagger/SwaggerConfig.kt
  module-presentation/src/main/kotlin/site/yourevents/config/swagger/annnotation/DisableSwaggerSecurity.kt
  module-presentation/src/main/kotlin/site/yourevents/health/api/HealthApi.kt
  module-presentation/src/main/kotlin/site/yourevents/health/api/HealthController.kt
  module-presentation/src/main/resources/application-dev.yml
  module-presentation/src/main/resources/application-local.yml
  module-presentation/src/main/resources/application.yml
Labels: ⚙️ chore

#10 chore: Sentry 구축 및 Docker 이미지 빌드 오류 수정
  module-infrastructure/monitoring/build.gradle.kts
  module-infrastructure/monitoring/src/main/kotlin/site/yourevents/sentry/SentryConfig.kt
  module-infrastructure/monitoring/src/main/resources/console-appender.xml
  module-infrastructure/monitoring/src/main/resources/logback-spring.xml
  module-presentation/build.gradle.kts
  module-presentation/src/main/resources/application-dev.yml
  module-presentation/src/main/resources/application-local.yml
  settings.gradle.kts
Labels: 🐛 bug, ⚙️ chore

#14 chore: 모니터링 환경 구축
  module-infrastructure/monitoring/build.gradle.kts
  module-infrastructure/security/src/main/kotlin/site/yourevents/SecurityConfig.kt
  module-presentation/src/main/resources/application-dev.yml
  module-presentation/src/main/resources/application-local.yml
Labels: ⚙️ chore

#23 feat: 초대장 삭제 기능 구현
  module-domain/src/main/kotlin/site/yourevents/invitation/domain/Invitation.kt
  module-domain/src/main/kotlin/site/yourevents/invitation/domain/InvitationVO.kt
  module-domain/src/main/kotlin/site/yourevents/invitation/exception/UnauthorizedException.kt
  module-domain/src/main/kotlin/site/yourevents/invitation/port/in/InvitationUseCase.kt
  module-domain/src/main/kotlin/site/yourevents/invitation/service/InvitationService.kt
  module-domain/src/main/kotlin/site/yourevents/invitationinformation/domain/InvitationInformationVO.kt
  module-domain/src/main/kotlin/site/yourevents/invitationinformation/service/InvitationInformationService.kt
  module-domain/src/main/kotlin/site/yourevents/invitationthumnail/domain/InvitationThumbnailVO.kt
  module-domain/src/main/kotlin/site/yourevents/invitationthumnail/service/InvitationThumbnailService.kt
  module-domain/src/test/kotlin/site/yourevents/guest/domain/GuestTest.kt
  module-domain/src/test/kotlin/site/yourevents/guest/domain/GuestVOTest.kt
  module-domain/src/test/kotlin/site/yourevents/guest/service/GuestServiceTest.kt
  module-domain/src/test/kotlin/site/yourevents/invitation/domain/InvitationTest.kt
  module-domain/src/test/kotlin/site/yourevents/invitation/domain/InvitationVOTest.kt
  module-domain/src/test/kotlin/site/yourevents/invitation/service/InvitationServiceTest.kt
  module-domain/src/test/kotlin/site/yourevents/invitationinformation/domain/InvitationInformationTest.kt
  module-domain/src/test/kotlin/site/yourevents/invitationinformation/domain/InvitationInformationVOTest.kt
  module-domain/src/test/kotlin/site/yourevents/invitationinformation/service/InvitationInformationServiceTest.kt
  module-domain/src/test/kotlin/site/yourevents/invitationthumbnail/domain/InvitationThumbnailTest.kt
  module-domain/src/test/kotlin/site/yourevents/invitationthumbnail/domain/InvitationThumbnailVOTest.kt
  module-domain/src/test/kotlin/site/yourevents/invitationthumbnail/service/InvitationThumbnailServiceTest.kt
  module-infrastructure/persistence-db/src/main/kotlin/site/yourevents/invitation/entity/InvitationEntity.kt
  module-infrastructure/persistence-db/src/main/kotlin/site/yourevents/invitation/repository/InvitationJPARepository.kt
  module-infrastructure/persistence-db/src/main/kotlin/site/yourevents/invitation/repository/InvitationRepository.kt
  module-infrastructure/persistence-db/src/test/kotlin/site/yourevents/guest/repository/GuestRepositoryTest.kt
  module-infrastructure/persistence-db/src/test/kotlin/site/yourevents/invitation/repository/InvitationRepositoryTest.kt
  module-infrastructure/persistence-db/src/test/kotlin/site/yourevents/invitationinformation/repository/InvitationInformationRepositoryTest.kt
  module-infrastructure/persistence-db/src/test/kotlin/site/yourevents/invitationthumbnail/repository/InvitationThumbnailRepositoryTest.kt
  module-presentation/src/main/kotlin/site/yourevents/invitation/api/InvitationApi.kt
  module-presentation/src/main/kotlin/site/yourevents/invitation/api/InvitationController.kt
  module-presentation/src/main/kotlin/site/yourevents/invitation/dto/response/CreateInvitationResponse.kt
  module-presentation/src/main/kotlin/site/yourevents/invitation/facade/InvitationFacade.kt
  module-presentation/src/main/resources/application-dev.yml
  module-presentation/src/test/kotlin/site/yourevents/invitation/facade/InvitationFacadeTest.kt
Labels: ✨ feature, ♻️ refactor

#26 feat: 초대장 정보 조회 기능 구현
  module-domain/src/main/kotlin/site/yourevents/guest/service/GuestService.kt
  module-domain/src/main/kotlin/site/yourevents/invitation/port/in/InvitationUseCase.kt
  module-domain/src/main/kotlin/site/yourevents/invitation/service/InvitationService.kt
  module-domain/src/test/kotlin/site/yourevents/invitation/service/InvitationServiceTest.kt
  module-infrastructure/persistence-db/src/main/kotlin/site/yourevents/guest/repository/GuestJPARepository.kt
  module-presentation/src/main/kotlin/site/yourevents/common/GlobalExceptionHandler.kt
  module-presentation/src/main/kotlin/site/yourevents/invitation/api/InvitationApi.kt
  module-presentation/src/main/kotlin/site/yourevents/invitation/api/InvitationController.kt
  module-presentation/src/main/kotlin/site/yourevents/invitation/dto/response/InvitationInfoResponse.kt
  module-presentation/src/main/kotlin/site/yourevents/invitation/facade/InvitationFacade.kt
  module-presentation/src/test/kotlin/site/yourevents/invitation/facade/InvitationFacadeTest.kt
Labels: ✨ feature, ♻️ refactor, ✅ test

#28 bug: No static resource 에러 해결
  module-infrastructure/security/src/main/kotlin/site/yourevents/SecurityConfig.kt
Labels: 🐛 bug

#36 feat: 초대장 발송자 여부 확인 기능 구현
  .github/workflows/cd-dev.yml
  module-domain/src/main/kotlin/site/yourevents/invitation/port/in/InvitationUseCase.kt
  module-domain/src/main/kotlin/site/yourevents/invitation/port/out/InvitationPersistencePort.kt
  module-domain/src/main/kotlin/site/yourevents/invitation/service/InvitationService.kt
  module-domain/src/test/kotlin/site/yourevents/invitation/service/InvitationServiceTest.kt
  module-infrastructure/persistence-db/src/main/kotlin/site/yourevents/invitation/repository/InvitationJPARepository.kt
  module-infrastructure/persistence-db/src/main/kotlin/site/yourevents/invitation/repository/InvitationRepository.kt
  module-presentation/src/main/kotlin/site/yourevents/invitation/api/InvitationApi.kt
  module-presentation/src/main/kotlin/site/yourevents/invitation/api/InvitationController.kt
  module-presentation/src/main/kotlin/site/yourevents/invitation/facade/InvitationFacade.kt
  module-presentation/src/main/resources/application-dev.yml
  module-presentation/src/test/kotlin/site/yourevents/invitation/facade/InvitationFacadeTest.kt
Labels: ✨ feature, ✅ test
